NEW: Detail view created
nicolopezca/APP-itunes pull request #5
Opened 2022-01-19 11:15 UTC by nicolopezca

2022-01-20 08:56 UTC, Carlos-Monfort requested changes

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/VC/DetailViewController.swift
> +    var titleArtist: String?
Si necesitas dos variables para iniciar el viewController, igual sería interesante que te llegue todo el objeto Artist o crear un viewModel

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/VC/DetailViewController.swift
> +        }
Por principios SOLID una función solo debería de encargarse de una tarea. En este caso sería añadir la vista al viewController, por lo que el seteo del id tendríamos que separarlo a otra parte.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/VC/DetailViewController.swift
> +        self.title = titleArtist
No entiendo muy bien qué hace esta variable o dónde se usa

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewComponents/DetailCell.swift
> +        self.albumImage?.loadImageFromUrl(url: viewModel.thumbnail!, completion: nil)
Corrige el force unwrap que tienes ahí. 

Al completion no hace falta que le pases un Nil pues está implementado por defecto como nil. Podrías borrarlo.

El uso del self en este caso no es necesario, bórralo.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewModel/DetailViewModel.swift
> +import UIKit
El viewModel no tiene que tener ninguna referencia a UIKit, borra este import

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +
Borra el salto de línea innecesario

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +    private var artistId: Int?
Una buena práctica en la declaración de variables es ordenarlos primero con los IBOutlets y después con las variables de clase. Reorganiza esto.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +    }
Esta función no tiene sentido que sea pública, mejor que esté en la parte privada de la clase.

Por otra parte, no está contemplado el caso en que el id sea nulo y la función no entre dentro del if let. Ahora mismo si eso pasara la app se quedaría bloqueada. Implementa la parte del else.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +    func obtainId(id: Int) {
Mal naming. Si la función está como pública para que desde fuera le pasen el id, no tiene sentido el verbo obtener. Tendría más sentido usar algún otro como setId.

Por otra parte, en una función que solo tiene un parámetro de entrada es una buena costumbre ponerle una barra baja antes del nombre del parámetro para que no sea obligatorio donde vaya a usarse y quede más limpio. Ejemplo:

`func xxxx(_ nameParameter: Type)`

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +        }
Según los principios SOLID una función solo debería tener una responsabilidad. En este caso o separas lo que pasa después del set id en otra función a parte, o renombras la función para que tenga sentido que todo pase en esta misma función.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +            print(detailResponse.discs)
Borra el print

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
>  class DetailView: UIView, UITableViewDelegate, UITableViewDataSource {
Es buena práctica que las implementaciones de delegados de una clase queden en una extensión a parte. Deberías separar UITableViewDelegate y UITableViewDataSource cada uno en una extensión y que en cada una estén los métodos relacionados.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +        }
Función muy larga. Deberías refactorizarla para que no sobrepasara las 10-15 líneas.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +                if let title = discs.collectionName,
Por qué separarlo en dos if let?

El if let solo debería usarse en caso de que si no se cumple la condición a continuación siga ejecutándose código. En este caso el else no tiene implementación, o se la das o mejor usar un guard para estos casos.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
> +    func cellTapped(id: Int, artistName: String)
Si necesitas más de un dato, puede ser también una opción pasar directamente todo el objeto y no separarlo por variables.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
>  class HomeView: UIView, UITableViewDelegate, UITableViewDataSource {
Es buena práctica que las implementaciones de delegados de una clase queden en una extensión a parte. Deberías separar UITableViewDelegate y UITableViewDataSource cada uno en una extensión y que en cada una estén los métodos relacionados.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
> +        }
El if let solo debería usarse en caso de que si no se cumple la condición a continuación siga ejecutándose código. En este caso el else no tiene implementación, o se la das o mejor usar un guard para estos casos.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
>              if let artistName = artist.artistName,
El if let solo debería usarse en caso de que si no se cumple la condición a continuación siga ejecutándose código. En este caso el else no tiene implementación, o se la das o mejor usar un guard para estos casos.

2022-01-20 08:56 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +                   let thumbnail = discs.artworkUrl100,
El nombre de la variable artworkUrl100 igual podríamos renombrarlo sin el número o como thumbnail, lo que prefieras.

2022-01-20 10:49 UTC, nicolopezca commented on AppItunes/Detail/VC/DetailViewController.swift
> +        self.title = titleArtist
self.title es el titulo de todo el viewcontroller
Con eso le asigno el nombre del artista al titulo

2022-01-20 10:59 UTC, nicolopezca commented on AppItunes/Detail/Views/DetailView.swift
> +    }
Y en la parte del else que se haria? un return y ya para que no se bloquee?

2022-01-25 14:56 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewComponents/DetailCell.swift
> +        albumImage?.loadImageFromUrl(url: thumbnail)
Con lo fan que eres de los if let y en el sitio donde tiene más sentido, no lo usas XD

En este caso está bien porque es la última acción de esta función, pero si no, tendrías que haber utilizado un if let en vez del guard.

2022-01-25 16:16 UTC, Carlos-Monfort requested changes

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewModel/DetailViewModel.swift
> +    let discographies: Discography
Plurales solo para Arrays. Cámbialo a singular que es un objeto.

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewModel/DetailViewModel.swift
> +        return discographies.collectionName ?? discographies.artistName!
Esto no tiene ningún sentido. Haces un safe unwrapp para concatenarlo con un force unwrapp. Y además no tiene por qué tener nada que ver el collectionName con el ArtistName. Otra de las razones por las que te salía una celda rara. Quita ese valor por defecto y pon un espacio vacío u otra cosa.

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewModel/DetailViewModel.swift
> +            return "Date"
Este valor por defecto que me dijiste que estaba de prueba... emosido engañado

Además retornas todavía un string opcional y le das valor...

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewModel/DetailViewModel.swift
> +    func getFormattedDate(format: String) -> String {
Identa bien esta función

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
>          artistId = id
Para qué sirve este artistId aquí?

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +        return
Este return es innecesario

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +        if let id = artistId {
Sería mejor que en vez de tener la variable artistId como variable global y la función la cogiera de aquí, tuviese un parámetro de entrada que no fuese opcional y que fuese el id.

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
>          discs.forEach { discs in
Ahora que ya tienes hecho el forEach y de forma correcta, sería un buen momento para hacer lo mismo pero con un map.

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +    func checkData(data: Data?, response: URLResponse?) -> Data? {
CheckData hace más referencia a una función que devuelve un boolean. Checkdata está ok pues true.
Como no es el caso sería más interesante llamarla getData

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/ViewComponents/AuthorCell.swift
>      static let cellReuseIdentifier = "AuthorCell"
Esta me la acaban de hacer hoy a mí y me parece que tienen toda la razón. Así que es mejor tener esto así:

`static let identifier = String(describing: AuthorCell.self)`

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/ViewComponents/AuthorCell.swift
> +        if let author = viewModel.artist.artistName {
Esto no estaría correcto. El viewModel te tendría que construir el artistName desde el Artist como variables computadas. Igual que lo que has hecho en Discography

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/ViewComponents/AuthorCell.swift
> +        if let style = viewModel.artist.primaryGenreName {
Idem

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/ViewComponents/AuthorCell.swift
> +        if let firstDisk = viewModel.artist.collectionName {
Idem

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/ViewComponents/AuthorCell.swift
>              let discografia = "Discografia"
No es buena idea dejar strings a capón en el proyecto. Es el momento para que todos los strings que tengas los reemplaces por un NSLocalizedString.

https://www.hackingwithswift.com/example-code/uikit/how-to-localize-your-ios-app

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/ViewComponents/AuthorCell.swift
>              let extendedLabel = "..."
Cambiar a NSLocalizedString

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/ViewModel/ArtistViewModel.swift
>      var hasMoreThanTwo: Bool {
hasMoreThanTwo qué?

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
> +        guard let data =  checkData(data: data, response: response) else {
GetData, igual que antes.

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
>          artists.forEach { artist in
Cambiar a map

2022-01-25 16:16 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
> +    func checkData(data: Data?, response: URLResponse?) -> Data? {
Renombrar función

2022-01-27 09:29 UTC, Carlos-Monfort requested changes

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewModel/DetailViewModel.swift
>      init(discographies: Discography) {
Este nombre en el init también tiene que ser en singular

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewModel/DetailViewModel.swift
> +        return discography.thumbnail ?? URL(string: "http://lamiradadelreplicante.com/wp-content/uploads/2015/06/swift.jpg")
Podríamos poner las constantes en un enum privado dentro de la clase para que queden más organizadas:

```suggestion
       private enum Constants {
             static let defaultImageURL = "http://lamiradadelreplicante.com/wp-content/uploads/2015/06/swift.jpg"
       }
       
       // Y aquí quedaría tal que así
       return discography.thumbnail ?? URL(string: Constants.defaultImageURL)
```

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +            let detailResponse = try prepareDecoder().decode(DiscResponse.self, from: data)
En vez de prepareDecoder, llámala getDecoder()

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +        let id = id
Aquí en cambio es el típico lugar donde sería mejor poner un guard en vez de un if let. Y de hecho podrías usar solo un guard que contenga las dos comprobaciones para id y url como hemos hecho en otros sitios de la app.

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
>              guard let url = URL(string: "https://itunes.apple.com/lookup?id=\(id)&entity=album") else {
Podríamos poner este string en un enum de constantes también.

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +            .filter { $0.wrapperType == "collection" }
Enum de constantes para el string

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
Te podrías crear una clase que fuera un enum "TimeFormat" donde añadieras los diferentes tipos de formatos de fechas que hayas utilizado a lo largo de la app, y aquí en vez de pasarle este string a capón, le pasarías un TimeFormat.

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/en.lproj/Localizable.strings
> +"Discography" = "Discografia";
A discografía le falta la tilde

2022-01-27 09:29 UTC, Carlos-Monfort commented on AppItunes/en.lproj/Localizable.strings
> +"Extended" = "...";
En vez de "..." podrías poner un ver más o algo así, que se entiende mejor

2022-01-28 08:53 UTC, Carlos-Monfort requested changes

2022-01-28 08:53 UTC, Carlos-Monfort commented on AppItunes/Detail/ViewModel/DetailViewModel.swift
> +           }
Esto está mal identado. Otra buena práctica es poner este enum lo más arriba que puedas dentro de la clase.

2022-01-28 08:53 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +    func getDiscography(id: Int?, completion: @escaping ((([Discography]?) -> Void))) {
Sin id esta función no tiene sentido, no debería de ser opcional

2022-01-28 08:53 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +        guard let id = id else {return}
Borrar este guard al hacer id obligatorio

2022-01-28 08:53 UTC, Carlos-Monfort commented on AppItunes/Detail/Views/DetailView.swift
> +    private enum Constants {
Mover el enum arriba de la clase

2022-01-28 08:53 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
> +            print(itunesResponse.artists)
Borrar este print

2022-01-28 08:53 UTC, Carlos-Monfort commented on AppItunes/Home/Views/HomeView.swift
> +    }
Mover el enum arriba

2022-01-28 09:33 UTC, Carlos-Monfort approved these changes

2022-01-28 09:34 UTC, merged